In [1]:
import numpy as np
from cvxopt import matrix
from cvxopt import solvers

In [2]:
h = matrix(np.array([[0],[0],[0], [0],[0]]), tc='d')

In [3]:
Ad = matrix(np.array([[1,1,-1],[-1,-1,1],[-1,0,0], [0,-1,0],[0,0,-1]]), tc='d')

In [4]:
print(Ad)

[ 1.00e+00  1.00e+00 -1.00e+00]
[-1.00e+00 -1.00e+00  1.00e+00]
[-1.00e+00  0.00e+00  0.00e+00]
[ 0.00e+00 -1.00e+00  0.00e+00]
[ 0.00e+00  0.00e+00 -1.00e+00]



In [5]:
X = matrix(np.array([[0,0],[2,2],[2,0]]), tc='d')

In [6]:
Qd = matrix(np.array([[0,0,0],[0,8,-4],[0,-4,4]]), tc='d')

In [7]:
q = matrix(np.array([-1,-1,-1]), tc='d')

In [8]:
print(q)

[-1.00e+00]
[-1.00e+00]
[-1.00e+00]



In [9]:
sol = solvers.qp(Qd,q,Ad,h)

     pcost       dcost       gap    pres   dres
 0: -1.0341e+00 -2.3208e+00  9e+00  3e+00  2e+00
 1: -8.9236e-01 -1.7551e+00  1e+00  1e-01  7e-02
 2: -9.9966e-01 -1.0726e+00  8e-02  4e-03  2e-03
 3: -1.0000e+00 -1.0009e+00  1e-03  4e-05  2e-05
 4: -1.0000e+00 -1.0000e+00  1e-05  4e-07  2e-07
 5: -1.0000e+00 -1.0000e+00  1e-07  4e-09  2e-09
Optimal solution found.


In [10]:
print(sol['x'])

[ 5.00e-01]
[ 5.00e-01]
[ 1.00e+00]

